import type { HistoryFilter, HistoryEntry } from "@/types/history";

/* ─── Filter Tabs ─── */
export const HISTORY_FILTERS: HistoryFilter[] = [
  { label: "Semua", value: "all", icon: "list" },
  { label: "Daur Ulang", value: "recycle", icon: "recycling" },
  { label: "Withdraw", value: "withdraw", icon: "send" },
];

/* ─── History Entries ─── */
export const HISTORY_ENTRIES: HistoryEntry[] = [
  {
    id: "h1",
    icon: "recycling",
    label: "Botol PET 600ml",
    description: "Scan via mesin EcoBottle Mall Pondok Indah",
    date: "5 Apr 2026",
    time: "14:20",
    amount: "+Rp 500",
    type: "credit",
    status: "completed",
    category: "recycle",
  },
  {
    id: "h2",
    icon: "recycling",
    label: "Botol Kaca 330ml",
    description: "Scan via mesin EcoBottle Stasiun Sudirman",
    date: "5 Apr 2026",
    time: "10:45",
    amount: "+Rp 1.200",
    type: "credit",
    status: "completed",
    category: "recycle",
  },
  {
    id: "h3",
    icon: "send",
    label: "Withdraw ke GoPay",
    description: "Transfer instan ke akun GoPay",
    date: "4 Apr 2026",
    time: "18:00",
    amount: "-Rp 15.000",
    type: "withdraw",
    status: "completed",
    category: "withdraw",
  },
  {
    id: "h4",
    icon: "recycling",
    label: "Botol PET 1.5L",
    description: "Scan via mesin EcoBottle GBK",
    date: "4 Apr 2026",
    time: "09:30",
    amount: "+Rp 750",
    type: "credit",
    status: "completed",
    category: "recycle",
  },
  {
    id: "h5",
    icon: "shopping_bag",
    label: "Voucher Alfamart Rp 10.000",
    description: "Redeem reward di marketplace",
    date: "3 Apr 2026",
    time: "15:22",
    amount: "-Rp 10.000",
    type: "debit",
    status: "completed",
    category: "voucher",
  },
  {
    id: "h6",
    icon: "send",
    label: "Withdraw ke OVO",
    description: "Transfer regular ke akun OVO",
    date: "2 Apr 2026",
    time: "11:00",
    amount: "-Rp 20.000",
    type: "withdraw",
    status: "pending",
    category: "withdraw",
  },
  {
    id: "h7",
    icon: "recycling",
    label: "Botol PET 600ml x3",
    description: "Scan via mesin EcoBottle Blok M",
    date: "1 Apr 2026",
    time: "16:40",
    amount: "+Rp 1.500",
    type: "credit",
    status: "completed",
    category: "recycle",
  },
  {
    id: "h8",
    icon: "recycling",
    label: "Botol HDPE 1L",
    description: "Scan via mesin EcoBottle Kemang",
    date: "31 Mar 2026",
    time: "08:15",
    amount: "+Rp 600",
    type: "credit",
    status: "completed",
    category: "recycle",
  },
  {
    id: "h9",
    icon: "shopping_bag",
    label: "Voucher Indomaret Rp 5.000",
    description: "Redeem reward di marketplace",
    date: "30 Mar 2026",
    time: "20:10",
    amount: "-Rp 5.000",
    type: "debit",
    status: "completed",
    category: "voucher",
  },
  {
    id: "h10",
    icon: "send",
    label: "Withdraw ke GoPay",
    description: "Transfer instan ke akun GoPay",
    date: "28 Mar 2026",
    time: "14:55",
    amount: "-Rp 25.000",
    type: "withdraw",
    status: "completed",
    category: "withdraw",
  },
];
